# Generated by Django 5.2.16 on 2026-08-01 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('praticiens', '0005_praticien_secteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleELearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('duree', models.CharField(help_text="Ex: '4h30'", max_length=20)),
                ('niveau', models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Avancé', 'Avancé'), ('Obligatoire', 'Obligatoire')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('lien_video', models.URLField(blank=True, help_text='Lien vers le module (YouTube non répertorié, Vimeo...).')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('termine', models.BooleanField(default=False)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('praticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_elearning', to='praticiens.praticien')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='elearning.moduleelearning')),
            ],
            options={
                'unique_together': {('praticien', 'module')},
            },
        ),
    ]
