# Generated by Django 5.2.16 on 2026-08-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('categorie', models.CharField(choices=[('Congrès', 'Congrès'), ('Atelier', 'Atelier'), ('Webinaire', 'Webinaire'), ('DPC', 'DPC')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text="Laisser vide si l'événement dure un seul jour.", null=True)),
                ('lieu', models.CharField(max_length=200)),
                ('prix', models.CharField(help_text="Ex: '85 000 FCFA' ou 'Gratuit (membres)'", max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Séparés par des virgules, ex: Implantologie, Endodontie', max_length=250)),
                ('places_totales', models.PositiveIntegerField()),
                ('places_prises', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False, help_text="Affiché en grand format 'Événement Phare' en haut de page.")),
                ('description', models.TextField(blank=True, help_text="Programme détaillé, affiché au clic sur 'Détails'.")),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
    ]
