# Generated by Django 6.0.7 on 2026-07-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Praticien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_inscription', models.CharField(max_length=20, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('radie', 'Radié')], default='actif', max_length=20)),
                ('date_inscription', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='praticiens/')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
