# Generated by Django 5.2.16 on 2026-07-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praticiens', '0003_praticien_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticien',
            name='diplome',
            field=models.FileField(blank=True, null=True, upload_to='diplomes/'),
        ),
        migrations.AlterField(
            model_name='praticien',
            name='numero_inscription',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='praticien',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('radie', 'Radié'), ('refuse', 'Demande refusée')], default='en_attente', max_length=20),
        ),
    ]
