# Generated by Django 5.2.16 on 2026-08-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praticiens', '0004_praticien_diplome_alter_praticien_numero_inscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticien',
            name='secteur',
            field=models.CharField(choices=[('liberal', 'Chirurgien-Dentiste libéral'), ('secteur_public', 'Salarié secteur public'), ('secteur_prive', 'Salarié secteur privé'), ('mixte', 'Exercice mixte')], default='liberal', max_length=20),
        ),
    ]
