# Generated by Django 5.2.16 on 2026-08-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identifiant technique unique, ex: attestation_formation_anesthesie', unique=True)),
                ('titre', models.CharField(max_length=150)),
                ('corps_html', models.TextField(help_text='Contenu HTML du document (utilisez les mêmes styles CSS que les autres modèles). Variables disponibles pour un praticien : {{ praticien.nom }}, {{ praticien.prenom }}, {{ praticien.numero_inscription }}, {{ praticien.specialite }}, {{ praticien.ville }}, {{ date_edition }}. Pour une attestation de formation, en plus : {{ participation.formation.nom }}, {{ participation.formation.date_debut }}, {{ participation.formation.date_fin }}, {{ participation.heures_obtenues }}.')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modèle de document',
                'verbose_name_plural': 'Modèles de documents',
            },
        ),
    ]
