# Generated by Django 5.2.16 on 2026-08-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTelechargeable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('juridique', 'Modèles Juridiques (Praticiens)'), ('etudiant', 'Ressources Étudiantes')], max_length=20)),
                ('fichier', models.FileField(upload_to='bibliotheque/')),
                ('date_maj', models.DateField(auto_now=True, help_text='Mise à jour automatique à chaque modification.')),
            ],
            options={
                'ordering': ['categorie', 'titre'],
            },
        ),
    ]
