# Generated by Django 5.2.16 on 2026-08-05 14:31

import cotisations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('praticiens', '0005_praticien_secteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremeCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur', models.CharField(choices=[('liberal', 'Chirurgien-Dentiste libéral'), ('secteur_public', 'Salarié secteur public'), ('secteur_prive', 'Salarié secteur privé'), ('mixte', 'Exercice mixte')], max_length=20, unique=True)),
                ('montant', models.PositiveIntegerField(help_text='Montant annuel en FCFA.')),
            ],
            options={
                'verbose_name': 'Barème de cotisation',
                'verbose_name_plural': 'Barème des cotisations',
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('montant', models.PositiveIntegerField(help_text='En FCFA. Calculé automatiquement selon le secteur si laissé à 0.')),
                ('date_echeance', models.DateField(default=cotisations.models.echeance_par_defaut)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('en_retard', 'En retard')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('methode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('autre', 'Autre')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='N° de reçu, référence de virement, etc.', max_length=100)),
                ('praticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='praticiens.praticien')),
            ],
            options={
                'ordering': ['-annee', 'praticien__nom'],
                'unique_together': {('praticien', 'annee')},
            },
        ),
    ]
