# Generated by Django 5.2.16 on 2026-08-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exposant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('Équipements', 'Équipements'), ('Pharmacie', 'Pharmacie'), ('Imagerie', 'Imagerie'), ('Prothèse', 'Prothèse'), ('Implants', 'Implants'), ('Instrumentation', 'Instrumentation')], max_length=30)),
                ('produits', models.CharField(help_text='Séparés par des virgules, ex: Fauteuils dentaires, Turbines', max_length=300)),
                ('stand', models.CharField(help_text='Ex: A-12', max_length=20, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['stand'],
            },
        ),
        migrations.CreateModel(
            name='ReservationStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('pays', models.CharField(max_length=100)),
                ('categorie_souhaitee', models.CharField(choices=[('Équipements', 'Équipements'), ('Pharmacie', 'Pharmacie'), ('Imagerie', 'Imagerie'), ('Prothèse', 'Prothèse'), ('Implants', 'Implants'), ('Instrumentation', 'Instrumentation')], max_length=30)),
                ('message', models.TextField(blank=True, help_text="Précisions sur les produits/besoins de l'entreprise.")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
    ]
