# Generated by Django 5.2.16 on 2026-08-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposant',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo de l'entreprise (facultatif).", null=True, upload_to='exposants/'),
        ),
    ]
