# Generated by Django 5.2.16 on 2026-08-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0002_exposant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposant',
            name='photo_stand',
            field=models.ImageField(blank=True, help_text='Photo du stand ou des produits exposés (facultatif).', null=True, upload_to='exposants/photos/'),
        ),
    ]
