# Generated by Django 5.2.16 on 2026-08-02 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etablissement', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=150)),
                ('periode', models.CharField(help_text='Ex: Sep–Déc 2025', max_length=100)),
                ('niveau_requis', models.CharField(help_text='Ex: D3 / D4', max_length=50)),
                ('places_totales', models.PositiveIntegerField()),
                ('places_prises', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['etablissement'],
            },
        ),
        migrations.CreateModel(
            name='CandidatureStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('niveau_actuel', models.CharField(help_text='Ex: D3', max_length=50)),
                ('cv', models.FileField(blank=True, null=True, upload_to='candidatures_stages/')),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='stages.stage')),
            ],
            options={
                'ordering': ['-date_candidature'],
            },
        ),
    ]
