# Generated by Django 5.2.16 on 2026-08-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembreConseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Dr. Adama Kaboré', max_length=150)),
                ('fonction', models.CharField(help_text='Ex: Président, Vice-Président, Trésorier...', max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Facultatif : initiales affichées si absente.', null=True, upload_to='conseil/')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Les membres avec le plus petit nombre s'affichent en premier.")),
            ],
            options={
                'verbose_name': 'Membre du Conseil',
                'verbose_name_plural': 'Membres du Conseil',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
    ]
