# Generated by Django 5.2.16 on 2026-08-01 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('categorie', models.CharField(choices=[('Formation', 'Formation'), ('Réglementation', 'Réglementation'), ('Alerte sanitaire', 'Alerte sanitaire'), ('Santé publique', 'Santé publique'), ('International', 'International'), ('Déontologie', 'Déontologie')], max_length=30)),
                ('extrait', models.TextField(help_text='Court résumé affiché dans les listes (1-2 phrases).')),
                ('contenu', models.TextField(blank=True, help_text="Texte complet de l'article.")),
                ('auteur', models.CharField(blank=True, max_length=150)),
                ('a_la_une', models.BooleanField(default=False, help_text="Une seule actualité à la fois devrait être 'à la une' idéalement.")),
                ('date_publication', models.DateField(default=django.utils.timezone.now)),
                ('temps_lecture', models.CharField(blank=True, help_text="Calculé automatiquement si laissé vide (ex: '3 min').", max_length=20)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
