# Generated by Django 5.2.16 on 2026-08-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, help_text="Photo affichée juste après le titre de l'article (facultatif).", null=True, upload_to='actualites/'),
        ),
    ]
