# Generated by Django 5.2.16 on 2026-07-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('praticiens', '0002_alter_praticien_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('horaires', models.CharField(blank=True, max_length=255)),
                ('est_de_garde', models.BooleanField(default=False)),
                ('praticiens', models.ManyToManyField(blank=True, related_name='cliniques', to='praticiens.praticien')),
            ],
            options={
                'ordering': ['ville', 'nom'],
            },
        ),
    ]
