# Generated by Django 5.2.16 on 2026-07-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinique',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
