# Generated by Django 5.2.16 on 2026-08-01 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('praticiens', '0004_praticien_diplome_alter_praticien_numero_inscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('heures', models.PositiveIntegerField(help_text="Nombre d'heures DPC validées par cette formation")),
                ('lieu', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_obtenues', models.PositiveIntegerField()),
                ('valide', models.BooleanField(default=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='formations.formation')),
                ('praticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='praticiens.praticien')),
            ],
            options={
                'unique_together': {('praticien', 'formation')},
            },
        ),
    ]
